### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by ghost** [saadnpq/matrixcli#19]
While using matrix.org server for log in I got this error
```
logging in ....
Traceback (most recent call last):
  File "/usr/local/bin/matrixcli", line 4, in <module>
    __import__('pkg_resources').run_script('matrixcli==0.1', 'matrixcli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/dist-packages/matrixcli-0.1-py3.9.egg/EGG-INFO/scripts/matrixcli", line 364, in <module>
  File "/usr/local/lib/python3.9/dist-packages/matrix_client-0.4.0.dev0-py3.9.egg/matrix_client/client.py", line 297, in login
  File "/usr/local/lib/python3.9/dist-packages/matrix_client-0.4.0.dev0-py3.9.egg/matrix_client/client.py", line 588, in _sync
KeyError: 'presence'
```

**Comment by Koakuma-spec** [comment]
I'm getting a very similar issue. I'm logging in by doing `matrixcli -c config.py`.

```logging in ....
Traceback (most recent call last):
  File "/usr/bin/matrixcli", line 4, in <module>
    __import__('pkg_resources').run_script('matrixcli==0.1', 'matrixcli')
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1570, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.10/site-packages/matrixcli-0.1-py3.10.egg/EGG-INFO/scripts/matrixcli", line 364, in <module>
  File "/usr/lib/python3.10/site-packages/matrix_client-0.4.0.dev0-py3.10.egg/matrix_client/client.py", line 297, in login
  File "/usr/lib/python3.10/site-packages/matrix_client-0.4.0.dev0-py3.10.egg/matrix_client/client.py", line 596, in _sync
KeyError: 'leave'
```
what does this mean
